version: "3.8"

services:
  core:
    image: localhost:5000/core:${DOCKER_IMAGE_TAG_CI}
    build:
      args:
        - RUN_POETRY_INSTALL_AT_BUILD_TIME=true
      context: ../../
      dockerfile: environments/Dockerfile
    tty: true
    volumes:
        - ../../:/home/challenger/chaosforge
